### ISSUE TITLE
AI is broken

### ISSUE THREAD

**Issue by Bountyover** [DigglesMods/ChangeGameSettings#3]
Hello

I have polish version of the game and looks like this mod is breaking the AI. After installing it, clans on deathmatch are not doing anything. I don't even need to change settings. Just installing the mod is disabling their AI

I was also testing it several times using commands:

ai init 0 data/scripts/ai/std_ai.tcl
ai enable 0

that allows AI to play your clan. I've noticed a lot of things AI is doing wrong but that's for another topic.

**Comment by cech12** [comment]
Hey!

Thanks for submitting this Issue!
Can you please upload the following game files before **and** after modding:

- Data/Scripts/ai/change_std_ai.tcl
- Data/Scripts/classes/zwerg/change_z_events.tcl
- Data/Scripts/classes/zwerg/change_z_procs.tcl
- Data/Scripts/classes/zwerg/change_z_spare_main.tcl
- Data/Scripts/misc/change_genattribs.tcl
- Data/Scripts/misc/change_utility.tcl

Thanks a lot. :)

**Comment by Bountyover** [comment]
There's no prefix "change" in them. Do you mean game files or those in "mods" folder?

**Comment by cech12** [comment]
Oh sorry xD 
I meant the files without the prefix "change_". :D

**Comment by Bountyover** [comment]
It have made a copy of itself. Hope it's normal :D

**Comment by Bountyover** [comment]
It have made a copy of itself. Hope it's normal :D 
[before.zip](https://github.com/DigglesMods/ChangeGameSettings/files/2459869/before.zip)
[after.zip](https://github.com/DigglesMods/ChangeGameSettings/files/2459870/after.zip)

**Comment by cech12** [comment]
Thanks a lot! 
Yes the copy is important for restoring the original state of the files. ;)
I will analyze your problem soon.

**Comment by cech12** [comment]
Okay I found the problem.
The _std_ai.tcl_ had no access to the get_civ_state method of the _utility.tcl_
Fixed in mod version  v1.2

You can test it, if you want. :D

**Comment by Bountyover** [comment]
Everything works now

Thank you!

**Comment by Bountyover** [comment]
I found another problem...now they're not making babies xd

**Comment by cech12** [comment]
Ooops xD
Okay, I will check that out. ^^

**Comment by cech12** [comment]
I found and fixed the problem in version 1.3. 
Thanks for your feedback!
It would be nice, when you test it. :D

**Comment by Bountyover** [comment]
Looks like everything is fine now. Nice work!
